

/*
The ludic numbers are a set of numbers related to prime numbers, as they are generated by sieving. Below is the method to generate such numbers.

Generation of ludic numbers:
First take the natural numbers starting from 2.
[2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19 ...]
1 is the first ludic number -> Ludic = {1}.
Note that you should not remove every 1th-indexed number, despite 1 being ludic.

Take the first element from the resulting array: 2.
Remove every 2nd indexed number.
[3, 5, 7, 9, 11, 13, 15, 17, 19 ...]
The first deleted number is 2 -> Ludic = {1, 2}.

Take the first element from the resulting array: 3.
Remove every 3rd indexed number.
[5, 7, 11, 13, 17, 19 ...]
The first deleted number is 3 -> Ludic = {1, 2, 3}.

Take the first element from the resulting array: 5.
Remove every 5th number.
[7, 11, 13, 19 ...]
The first deleted number is 5 -> Ludic = {1, 2, 3, 5}.

etc...
Write a function to return an integer: the sum of the first n ludic numbers.
You can assume that 1 ≤ n ≤ 10000.

Sample Tests:
sumLudic(1) -> 1
sumLudic(10) -> 107
sumLudic(25) -> 1100
Algorithms
*/
// Solution
package kata

import "math/bits"

func SumLudic(n int) int {
	limit := 300000

	for {
		size := limit - 1
		bit := make([]int, size+1)

		for i := 1; i <= size; i++ {
			bit[i]++
			if j := i + (i & (-i)); j <= size {
				bit[j] += bit[i]
			}
		}

		update := func(i, delta int) {
			for ; i <= size; i += i & (-i) {
				bit[i] += delta
			}
		}

		logn := bits.Len(uint(size))
		findKth := func(k int) int {
			pos, rem := 0, k
			for pw := logn; pw >= 0; pw-- {
				if next := pos + (1 << uint(pw)); next <= size && bit[next] < rem {
					pos = next
					rem -= bit[next]
				}
			}
			return pos + 1
		}

		alive := size
		ludic := make([]int, 0, n)
		ludic = append(ludic, 1)
		ok := true

		for len(ludic) < n {
			if alive == 0 {
				ok = false
				break
			}
			step := findKth(1) + 1
			ludic = append(ludic, step)
			if len(ludic) == n {
				break
			}

			countThisPass := (alive-1)/step + 1
			for i := 1; i <= countThisPass; i++ {
				r := 1 + (i-1)*(step-1)
				idx := findKth(r)
				update(idx, -1)
			}
			alive -= countThisPass
		}

		if ok && len(ludic) == n {
			sum := 0
			for _, v := range ludic {
				sum += v
			}
			return sum
		}
		limit *= 2
	}
}