# Sum Even Fibonacci Numbers
# Write a func named SumEvenFibonacci that takes a parameter of type int and returns a value of type int
#
# Generate all of the Fibonacci numbers starting with 1 and 2 and ending on the highest number before exceeding the parameter's value
#
# Each new number in the Fibonacci sequence is generated by adding the previous two numbers - by starting with 1 and 2(the input could be smaller), the first 10 numbers will be:
#  1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
# Sum all of the even numbers you generate and return that int
# Example:
# sumEvenFibonacci(8) // returns 10 by adding the even values 2 and 8
# FUNDAMENTALS
# Solution
def SumEvenFibonacci(limit):
    a, b, c = 1, 1, 0
    while a <= limit:
        if not a % 2: c += a
        a, b = b, a + b
    return c