# You are given two strings s and t.
# String t is generated by random shuffling string s and then add one more letter at a random position.
# Return the letter that was added to t.
#
# Example 1:
#
# Input: s = "abcd", t = "abcde"
# Output: "e"
# Explanation: 'e' is the letter that was added.
# Example 2:
#
# Input: s = "", t = "y"
# Output: "y"
#
# Constraints:
# 0 <= s.length <= 1000
# t.length == s.length + 1
# s and t consist of lowercase English letters.
# Solution
class Solution:
    def findTheDifference(self, s: str, t: str) -> str:
        for i in s:
            if i in t:
                t = t.replace(i, '', 1)
        return t
# Solution 2
class Solution:
    def findTheDifference(self, s: str, t: str) -> str:
        x, y = {}, {}
        for i in s:
            x[i] = x.get(i, 0) + 1
        for i in t:
            if i not in x:
                return i
            y[i] = y.get(i, 0) + 1
            if y[i] > x[i]:
                return i