/*
You are given two strings, str1 and str2, of lengths n and m, respectively.

A string word of length n + m - 1 is defined to be generated by str1 and str2 if it satisfies the following conditions for each index 0 <= i <= n - 1:

If str1[i] == 'T', the substring of word with size m starting at index i is equal to str2, i.e., word[i..(i + m - 1)] == str2.
If str1[i] == 'F', the substring of word with size m starting at index i is not equal to str2, i.e., word[i..(i + m - 1)] != str2.
Return the lexicographically smallest possible string that can be generated by str1 and str2. If no string can be generated, return an empty string "".



Example 1:

Input: str1 = "TFTF", str2 = "ab"

Output: "ababa"

Explanation:

The table below represents the string "ababa"
Index	T/F	Substring of length m
0	'T'	"ab"
1	'F'	"ba"
2	'T'	"ab"
3	'F'	"ba"
The strings "ababa" and "ababb" can be generated by str1 and str2.

Return "ababa" since it is the lexicographically smaller string.

Example 2:

Input: str1 = "TFTF", str2 = "abc"

Output: ""

Explanation:

No string that satisfies the conditions can be generated.

Example 3:

Input: str1 = "F", str2 = "d"

Output: "a"



Constraints:

1 <= n == str1.length <= 104
1 <= m == str2.length <= 500
str1 consists only of 'T' or 'F'.
str2 consists only of lowercase English characters.
*/
// Solution
// C++ O(NM^2) O(N + M) String Greedy
class Solution {
public:
    string generateString(string str1, string str2) {
        size_t n = str1.size(), m = str2.size();
        std::string output(n + m - 1, '*');
        for (size_t i = 0; i < n; ++i) {
            if (str1[i] == 'T') {
                for (size_t j = 0; j < m; ++j) output[i + j] = str2[j];
            }
        }
        for (size_t i = 0; i < n; ++i) {
            if (str1[i] == 'T') {
                if (output.substr(i, m) != str2) return "";
                continue;
            }
            if (output.substr(i, m) == str2) return "";
            for (size_t j = 0; j < m; ++j) {
                if (output[i + j] != '*') continue;
                bool was = true;
                for (size_t k = 0; k < 26; ++k) {
                    was = true;
                    output[i + j] = k + 'a';
                    size_t bound = (m > i ? 0 : i - m);
                    for (size_t z = bound; z < std::min(n, i + m); ++z) {
                        if (str1[z] == 'F' && (output.substr(z, m) == str2)) {
                            was = false;
                            break;
                        }
                    }
                    if (was) break;
                }
                if (!was) return "";
            }
        }
        return output;
    }
};